# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutuVote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoutuVote
  pod 'Firebase/Core'

  target 'YoutuVoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'YoutuVote-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoutuVote-tvOS

  target 'YoutuVote-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
